In [1]:
import numpy as np

seeds = [2221777491, 2873750246, 4067173416, 794519497, 3287624630, 3357287912, 1212880927, 2464917741,
949382604, 1898004827, 2947301415, 790253146, 717857433, 428724147, 1685527558, 943400827,
2654514605, 3579164172, 1769226289, 1832943298, 10586571, 3240865749, 3796889285, 4281504960,
3800820748, 356885, 1290249776, 4191694121, 2532234831, 1800111962, 4202311614, 2927266873]

class LFSR(object):

    def __init__(self, seed, taps=[2, 7, 22, 32]):
        self.seed = seed
        self.taps = taps
        self.state = '{0:032b}'.format(self.seed)[::-1] #bitstring

    def next(self):
        xor = 0
        for t in self.taps:
            xor += int(self.state[32-t])
        if xor%2 == 0.0:
            xor = 0
        else:
            xor = 1

        self.state = str(xor) + self.state[:-1]
        return xor

    def reset(self):
        self.state = '{0:032b}'.format(self.seed)[::-1]


def generateRandomMatrix():
    n_features = 128
    n_components = 32
    
    #initialise random matrix
    rij = np.zeros(shape=(n_features, n_components))

    #make sure that mem matches seeds
    if n_components != len(seeds):
        print("Error: n_components must equal len(seeds)")

    #initialise lfsrs - pseudo random number generators
    lfsrs = [LFSR(seeds[i]) for i in range(len(seeds))]

    #create random matrix
    for j in range(n_components):
        lfsr = lfsrs[j] #each dimension j represents a unique n_component and LFSR
        for i in range(n_features):
            rnd = lfsr.next()
            rnd = rnd*2 -1
            rij[i][j] = rnd
        lfsr.reset()

    return rij


rij = generateRandomMatrix()
print(rij, rij.shape, rij.dtype)

[[ 1.  1.  1. ...  1.  1.  1.]
 [-1. -1. -1. ... -1.  1. -1.]
 [-1. -1.  1. ...  1.  1. -1.]
 ...
 [ 1. -1. -1. ... -1.  1. -1.]
 [ 1.  1.  1. ... -1. -1. -1.]
 [-1. -1. -1. ...  1.  1. -1.]] (128, 32) float64


In [2]:
N = 10
n_features = 128
n_components = 32

np.random.seed(23)
x = np.random.rand(N*n_features).astype(np.float32)*2 - 1
X = x.reshape(-1, n_features)

print(np.dot(X, rij) * (np.sqrt(1.0/n_components)))

[[-0.27790921  0.52748799  0.98073113  1.02838642 -1.1041802  -1.71546226
  -3.18399894 -1.04175884  0.44072786 -1.0184754   2.11192715 -1.62595879
  -0.56444926 -0.66141929  0.23148981 -1.52308868  0.1083136  -0.63661777
  -0.7220238   1.08037403 -0.65279261  0.67103507  0.24839467  2.17099983
  -0.54710075  0.78272486 -0.08471762 -0.34614725 -0.15378484 -0.84266136
   0.83085521  1.84348799]
 [-0.76608036  0.45794382 -0.30020675 -0.61380786 -0.39260293 -0.06364442
  -0.32569161  0.65054643  1.50472457  1.73241264 -1.32353455 -0.49001871
   1.32404561 -1.66123875 -0.48660233 -1.75506393 -1.83499739 -0.54887131
  -1.16464778  0.13675523  0.66380669 -0.92720384  0.90714675  0.38257251
  -1.35357333  0.01125926  0.11333214  1.52714189  1.50509072 -0.61143032
   1.50432765  1.40014528]
 [-0.70541427 -0.38744241  0.17312174 -0.07318039 -0.79022734  1.93048822
   2.28449663  2.25285377  0.16735131 -0.58813169  0.76955107 -0.21823202
   1.01915585  0.23613187 -2.14979429 -0.79039711 -0.30968